language: swift
osx_image: xcode9.1

env:
  global:
    - LANG=en_US.UTF-8
script:
  - xcodebuild -workspace WBAlamofire.xcworkspace -scheme "WBAlamofire iOS" -destination "platform=iOS Simulator,name=iPhone 8"
after_success:
  - bash <(curl -s https://codecov.io/bash)
