# Like as SDWebImage but use Carthage. https://github.com/rs/SDWebImage/blob/master/.travis.yml
language: objective-c
osx_image: xcode9.1

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

before_install:
    - env
    - locale
    - brew update
    - brew upgrade carthage || true
    - carthage version
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Check if the library described by the podspec can be built
    - carthage bootstrap

    - echo Build as static library
    - xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    - xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire watchOS' -sdk watchsimulator -configuration Debug | xcpretty -c

    - echo Build as dynamic framework
    - xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire macOS' -sdk macosx -configuration Debug | xcpretty -c
    - xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c
    - xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire tvOS' -sdk appletvsimulator -configuration Debug | xcpretty -c
    - xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire watchOS' -sdk watchsimulator -configuration Debug | xcpretty -c

    - echo Build the Demo apps
    # mac demo (not complete)
    #- xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire' -sdk macosx -configuration Debug | xcpretty -c
    
    - xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire' -configuration Debug -destination 'name=iPhone 7' | xcpretty -c
    # tvos demo (not complete)
    #- xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire' -sdk appletvsimulator -configuration Debug | xcpretty -c
    # watchos demo (not complete)
    #- xcodebuild clean build -workspace WBAlamofire.xcworkspace -scheme 'WBAlamofire' -configuration Debug -destination 'name=iPhone 7' | xcpretty -c
    
after_success:
    - bash <(curl -s https://codecov.io/bash)
