language: swift
osx_image: xcode9.1

matrix:
  include:
    - osx_image: xcode9.1
      env: PLATFORM="iOS"
    - osx_image: xcode9.1
      env: PLATFORM="tvOS"
    - osx_image: xcode9.1
      env: PLATFORM="macOS"
env:
  global:
    - LANG=en_US.UTF-8
cache:
  - bundler
before_install:
  - brew update
  - brew upgrade carthage || true
  - carthage version
  - carthage bootstrap --platform $PLATFORM
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -workspace WBAlamofire.xcworkspace -scheme "WBAlamofire iOS" -destination "platform=iOS Simulator,name=iPhone 8"
  - xcodebuild -workspace WBAlamofire.xcworkspace -scheme "WBAlamofire macOS"
  - xcodebuild -workspace WBAlamofire.xcworkspace -scheme "WBAlamofire tvOS" -destination "platform=tvOS Simulator,name=Apple TV 4K"
  - xcodebuild -workspace WBAlamofire.xcworkspace -scheme "WBAlamofire watchOS" -destination "platform=watchOS Simulator,name=Apple Watch - 42mm"
after_success:
  - bash <(curl -s https://codecov.io/bash)
