language: objective-c
osx_image: xcode9.1

env:
  - ACTION=test  PLATFORM=Mac     DESTINATION='platform=OS X'
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'
  - ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'
  - ACTION=test  PLATFORM=watchOS DESTINATION='platform=watchOS Simulator,name=Apple Watch - 42mm'

script:
  - set -o pipefail && xcodebuild -scheme WBAlamofire -destination "$DESTINATION" $ACTION | xcpretty
