language: objective-c
osx_image: xcode9.1

matrix:
  include:
    - osx_image: xcode9.1
      env: PLATFORM="iOS"
    - osx_image: xcode9.1
      env: PLATFORM="tvOS"
    - osx_image: xcode9.1
      env: PLATFORM="macOS"
env:
  global:
    - LANG=en_US.UTF-8
cache:
  - bundler
before_install:
  - brew update
  - brew upgrade carthage || true
  - carthage version
  - carthage bootstrap --platform $PLATFORM
script:
  - bundle exec rake ci[$PLATFORM]
after_success:
  - bash <(curl -s https://codecov.io/bash)
